#pragma once

#include "operators/aggregate_operator.h"
#include "operators/delete_operator.h"
#include "operators/filter_operator.h"
#include "operators/hash_join_operator.h"
#include "operators/insert_operator.h"
#include "operators/limit_operator.h"
#include "operators/lock_rows_operator.h"
#include "operators/merge_join_operator.h"
#include "operators/nested_loop_join_operator.h"
#include "operators/orderby_operator.h"
#include "operators/projection_operator.h"
#include "operators/seqscan_operator.h"
#include "operators/update_operator.h"
#include "operators/values_operator.h"
